___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np


# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [10,20,30,40,50,60]
my_list

[10, 20, 30, 40, 50, 60]

In [3]:
list("abcd")

['a', 'b', 'c', 'd']

In [4]:
tuple("abcd")

('a', 'b', 'c', 'd')

In [5]:
set("abcd")

{'a', 'b', 'c', 'd'}

In [6]:
print(np.array(my_list))

[10 20 30 40 50 60]


In [7]:
# 10 ile 20 arasında yer alan sayılardan oluşan bir pyton
# listesi oluşturalım. range() fonksiyonu kullanalım
# daha sonra listemizi array dönüştürelim

In [8]:
np.array(list(range(10,20)))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
liste = list(range(10,20))

In [10]:
np.array(liste)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Why NumPy?

In [11]:
a1 = np.array([1,2,3,4,5])
b1 = np.array([5,5,5,5,5])

In [12]:
a1 * b1

array([ 5, 10, 15, 20, 25])

In [13]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[5,5,5,5]])
b1 = np.array([[3,3,3,3],[4,4,4,4],[1,2,3,4]])

In [14]:
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 5, 5, 5]])

In [15]:
b1

array([[3, 3, 3, 3],
       [4, 4, 4, 4],
       [1, 2, 3, 4]])

In [16]:
a1 * b1

array([[ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20]])

In [17]:
[[3,6,9,12],
[4,8,12,16]]

[[3, 6, 9, 12], [4, 8, 12, 16]]

In [18]:
# Nested lists without NumPy.
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
matrix_array = np.array(my_matrix)

In [20]:
print(matrix_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
matrix_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(matrix_array)

numpy.ndarray

## Built-in Methods

There are lots of built-in ways to generate Arrays

### ``arange``

Return evenly spaced values within a given interval.

In [23]:
np.arange(0,17,4)

array([ 0,  4,  8, 12, 16])

### **``zeros``, ``ones`` and ``full``**

Generate arrays of zeros or ones

In [24]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [25]:
np.zeros(6, dtype = float)

array([0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((4,4), dtype = float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((4,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [28]:
np.ones(3)

array([1., 1., 1.])

In [29]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [30]:
np.ones((3,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.ones((2,2), dtype=str)

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [32]:
np.ones((3,3), dtype = str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [33]:
np.zeros((3,3),dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [34]:
np.full((3, 3), "Python")

array([['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python']], dtype='<U6')

In [35]:
np.full((5,5),'10', dtype = int)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [36]:
np.full((2,2),3, dtype = str)

array([['3', '3'],
       ['3', '3']], dtype='<U1')

### ``linspace``
Return evenly spaced numbers over a specified interval.

In [37]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [38]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [39]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [40]:
np.linspace(0,20,25,endpoint=True)

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        , 10.83333333, 11.66666667,
       12.5       , 13.33333333, 14.16666667, 15.        , 15.83333333,
       16.66666667, 17.5       , 18.33333333, 19.16666667, 20.        ])

In [41]:
# equal pieces


In [42]:
np.linspace(0, 10, 51, dtype = "int")

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [43]:
np.linspace(0, 10, 51, dtype = int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

## ``eye``

Creates an [identity matrix](https://www.mathbootcamps.com/the-identity-matrix-and-its-properties/)

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(7,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### ``rand``
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

- ``(0, 5)`` = 1, 2, 3, 4
- ``(0, 5]`` = 1, 2, 3, 4, 5
- ``[0, 5)`` = 0, 1, 2, 3, 4
- ``[0, 5]`` = 0, 1, 2, 3, 4, 5

In [46]:
np.random.seed(101) #to get the same result everytime
np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])

In [47]:
np.random.seed(32)
np.random.randint(2,2000, size = 3)

array([ 729, 1581, 1927])

In [48]:
np.random.seed(101)
np.random.rand(2,2)

array([[0.51639863, 0.57066759],
       [0.02847423, 0.17152166]])

In [49]:
np.random.seed(101)
np.random.rand(2,2,2) #2 pieces of 2x2 array

array([[[0.51639863, 0.57066759],
        [0.02847423, 0.17152166]],

       [[0.68527698, 0.83389686],
        [0.30696622, 0.89361308]]])

### ``randn``

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [50]:
np.random.seed(101)
np.random.randn(5)

array([2.70684984, 0.62813271, 0.90796945, 0.50382575, 0.65111795])

In [51]:
np.random.seed(101)


In [52]:
import matplotlib.pyplot as plt

In [53]:
plt.hist(np.random.rand(20000), bins=20000)
plt.show()

In [54]:
np.random.randn(1903).mean()  # Standart normal distrubition gives mean of 0
# 1000 samples is good

-0.01966665132139106

In [55]:
np.random.randn(1903).std()**2  # Standart normal distrubition gives variance of 1

0.96047218552916

In [56]:
np.random.seed(101)
np.random.randn(2, 2, 2)

array([[[ 2.70684984,  0.62813271],
        [ 0.90796945,  0.50382575]],

       [[ 0.65111795, -0.31931804],
        [-0.84807698,  0.60596535]]])

### ``randint``
Return random integers from `low` (inclusive) to `high` (exclusive).

In [57]:
# [low, high)
np.random.seed(42)
np.random.randint(10, 20, 3)

array([16, 13, 17])

In [58]:
np.random.seed(42)
                      # the only int (8) refers to the high (stop)

In [59]:
np.random.seed(42)


In [60]:
np.random.seed(42)
np.random.randint(10, 20, size = (3, 4))

array([[16, 13, 17, 14],
       [16, 19, 12, 16],
       [17, 14, 13, 17]])

In [61]:
np.random.seed(42)
np.random.randint(1, [5, 10, 20])  # 3 different upper bounds

array([ 3,  4, 15])

In [62]:
np.random.seed(42)
                    # 3 different upper bounds with 5x3 matrix

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [82]:
arr = np.arange(10)

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.random.seed(42)
ranarr = np.random.randint(0, 20, 10)
ranarr

array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3])

## Reshape
Returns an array containing the same data with a new shape.

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### ``max``, ``min``, ``argmax``, ``argmin``

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [88]:
ranarr

array([ 6, 19, 14, 10,  7,  6, 18, 10, 10,  3])

In [89]:
ranarr.max()

19

In [90]:
ranarr.argmax()

1

In [69]:
ranarr.min()

3

In [91]:
ranarr.argmin()

9

## Some other attributes :
* ``ndim``: number of array dimensions.
* ``shape``: tuple of array dimensions.
* ``size``: Number of elements in the array.
* ``dtype``: data types of the array.

## ``shape``

Shape is an attribute that arrays have (not a method):

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
# Vector
arr.shape

(10,)

In [96]:
arrr = arr.reshape(5,2)

In [97]:
arrr.shape

(5, 2)

In [72]:
# Notice the two sets of brackets

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr.reshape(-1,5)  #if -1 used (10*1)/5= 2 auto calculated 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## ``dtype``

You can also grab the data type of the object in the array:

In [98]:
arr.dtype

dtype('int32')

## ``ndim``

In [76]:
# rows and columns = 2 dimensions
arr=arr.reshape(5, 2)
arr.ndim

2

In [77]:
arr.shape

(5, 2)

## ``size``

In [99]:
arr.size

10

In [79]:
arr.dtype

dtype('int32')

In [80]:
np.random.seed(42)


In [100]:
b

NameError: name 'b' is not defined

In [ ]:
b.ndim

# Concatenation of the Arrays

In [101]:
x = np.array([10, 20, 30])
y = np.array([33, 44, 55])

In [102]:
x + y

array([43, 64, 85])

In [106]:
np.concatenate([x,y])

array([10, 20, 30, 33, 44, 55])

### 2d matrix

In [107]:
a = np.array([[1,2,3], 
              [4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
b=a*10
b

array([[10, 20, 30],
       [40, 50, 60]])

In [109]:
np.concatenate([a,b],axis = 1)  # sütun bazlı concat ederken satır sayıyı sabit
# 

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [110]:
np.concatenate([a,b],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [113]:
arr1 = np.random.randint(1,10, size = (3,4))

In [115]:
arr2 = arr1 * 3

In [116]:
arr1

array([[3, 5, 3, 7],
       [5, 9, 7, 2],
       [4, 9, 2, 9]])

In [117]:
arr2

array([[ 9, 15,  9, 21],
       [15, 27, 21,  6],
       [12, 27,  6, 27]])

In [119]:
np.concatenate([arr1,arr2], axis = 0)

array([[ 3,  5,  3,  7],
       [ 5,  9,  7,  2],
       [ 4,  9,  2,  9],
       [ 9, 15,  9, 21],
       [15, 27, 21,  6],
       [12, 27,  6, 27]])

In [120]:
arr1

array([[3, 5, 3, 7],
       [5, 9, 7, 2],
       [4, 9, 2, 9]])

In [121]:
arr2

array([[ 9, 15,  9, 21],
       [15, 27, 21,  6],
       [12, 27,  6, 27]])

In [122]:
np.concatenate([arr1,arr2], axis = 1)

array([[ 3,  5,  3,  7,  9, 15,  9, 21],
       [ 5,  9,  7,  2, 15, 27, 21,  6],
       [ 4,  9,  2,  9, 12, 27,  6, 27]])

# Splitting of the Arrays

In [125]:
x = np.array([1, 2, 3, 99, 88, 33, 22, 11])

x

array([ 1,  2,  3, 99, 88, 33, 22, 11])

In [ ]:
#3 and 5 split index

In [126]:
np.split(x,[3,5]) 

[array([1, 2, 3]), array([99, 88]), array([33, 22, 11])]

In [127]:
x[:3]

array([1, 2, 3])

In [128]:
x[2:6]

array([ 3, 99, 88, 33])

If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[3, 5]`` would, for ``axis=0``, result in
- ``ary[:3]``
- ``ary[3:5]``
- ``ary[5:]``

In [129]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 88]), array([33, 22, 11])]

In [130]:
a,b,c = np.split(x, [3,5])

In [131]:
a

array([1, 2, 3])

In [132]:
b

array([99, 88])

In [133]:
c

array([33, 22, 11])

In [136]:
np.split(x,[4,5])

[array([ 1,  2,  3, 99]), array([88]), array([33, 22, 11])]

In [137]:
np.split(x,[3,6])

[array([1, 2, 3]), array([99, 88, 33]), array([22, 11])]

In [141]:
ornek = np.array([2012,6,15])

In [151]:
yıl,ay, gün = np.split(ornek, [1,2])

In [149]:
yıl

array([2012])

In [152]:
ay

array([6])

In [153]:
gün

array([15])

The number of the elements is divisible by 4, otherwise raises an error. If the argument (here is 4) is not enclosed by square brackets, then it means dividing into 4 pieces.

In [ ]:
np.split(x, 2) #8 element only divisible by 2,4,8

### 2d matrix

In [154]:
m = np.arange(24).reshape(4, 6)
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
 #split from 1 and 3

In [156]:
np.split(m,[1,3])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

In [157]:
m

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [160]:
np.split(m,[1,3])

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]])]

In [ ]:
# Focus on double square brackets. All rows are still 2d-arrays.

 #split into 2

In [ ]:
m

# Sorting of the Arrays

In [161]:
v = np.array([2,1,4,3,5])

v

array([2, 1, 4, 3, 5])

In [165]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
 # changed inplace
    

In [ ]:
v

### 2d matrix

In [ ]:
np.random.seed(42)
twoD = 

twoD

In [ ]:
                            # the rows are sorted from upper to lower and column by column

In [ ]:
                        # the columns are sorted from left to right and row by row

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr=np.arange(1,21).reshape(4,5)

In [ ]:
arr

In [ ]:
# Get values in a range


In [ ]:
# Get values in a range


In [ ]:
# arr[start:stop:step], odds


In [ ]:
# arr[start:stop:step], evens


## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)

#Show
arr

In [166]:
a=[0,0,0,6,8,10]

In [ ]:
a

In [167]:
# Reset array, we'll see why I had to reset in  a moment
arr=np.arange(10,21)

# Show
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# Important notes on Slices
slice_of_arr=arr[0:3]

# Show slice
slice_of_arr

In [169]:
arr[:5] = 88

In [170]:
arr

array([88, 88, 88, 88, 88, 15, 16, 17, 18, 19, 20])

In [ ]:
#To get a copy, need to be explicit
arr_copy=arr.copy()
arr_copy

In [ ]:
# We can assign a list of values in an exact dimension
arr_copy[:4]=[0,0,0,0]

In [ ]:
arr_copy

In [ ]:
arr

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [ ]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

In [ ]:
#Indexing row


In [ ]:
# Getting individual element value


In [ ]:
# 2D array slicing

# Shape (2,2) from bottom right corner


In [ ]:

arr_2d

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
v=np.arange(0,30,3)
v

In [ ]:
v[3]

In [ ]:
# we can select separate elements using their indices in a list


<h3>any_array[[row indices], [column indices]]</h3>

In [ ]:
jj=np.arange(1,17).reshape(4,4)

In [ ]:
jj

In [ ]:
# let's select separate values of 6 and 8
 

In [ ]:
# this time let's select separate values of 1, 10 and 16


### Using ***basic index*** and ***fancy index*** together

In [ ]:
jj

In [ ]:
# let's select 5 and 7 which are in the same row (index 1)


In [ ]:
# let's select 3 and 15 which are the same column (index 2)


### Using ***basic slicing*** and ***fancy index*** together

In [ ]:
jj

In [ ]:
# let's select two middle columns


In [ ]:
# let's select center small square (4 elements)


In [ ]:
# remember, how normal slicing is executed


In [174]:
arr = np.random.randint(1,20, size = 5)
arr[:3]

array([14, 17,  4])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [175]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [176]:
arr>6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
# take different than two and equal or smaller than 8


# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [ ]:
import numpy as np
arr = np.arange(0,10)*5

In [ ]:
arr

In [ ]:
import warnings
warnings.filterwarnings('ignore') #for 0 division error

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

In [ ]:
# Also warning, but not an error instead infinity
1/arr

In [ ]:
arr**3

In [ ]:
v=np.array([1,2,3,4,5])+10
v

In [ ]:
v*10 / 10-1

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
arr

In [ ]:
#Taking Square Roots


In [ ]:
#Calcualting exponential (e^)


In [ ]:
# same as arr.max()


In [ ]:
# there are many trigonometric functions


In [ ]:
np.sin(np.pi/2)

In [ ]:
v

In [ ]:
x1=np.arange(5,46,5).reshape(3,3)
x2=np.arange(3)

In [ ]:
x1

In [ ]:
x2

In [ ]:
# v**3


In [ ]:
# v % 5


In [ ]:
#absolute


## Statistical Calculations

In [ ]:
v=np.array([1,1,2,2,3,3,3])
v

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___