In [1]:
import pandas as pd
import numpy as np

### Statiscial Calculation

In [3]:
v = np.array([1,1,2,2,3,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3, 3])

In [5]:
np.mean(v)  # ortalama alma

2.25

In [6]:
np.median(v)  # ortanca bulma

2.5

In [8]:
np.var(v)  # variation varyasyon



0.6875

### A sample solve in linear Algebra using Numpy

In [18]:
a = np.array([[3,1],[1,2]])
b = np.array([[9,8]])

In [19]:
a

array([[3, 1],
       [1, 2]])

In [20]:
b

array([[9, 8]])

In [23]:
np.linalg.solve()

TypeError: _solve_dispatcher() missing 1 required positional argument: 'b'

In [26]:
a = pd.Series([1,2,3], index = ["a","b","c"])
a["a
  
  "]

1