In [ ]:
https://medium.com/deep-learning-turkiye/python-ile-veri-bilimine-dal%C4%B1%C5%9F-3f069260ebda

Bir veri bilimi projesinin aşamalarını soyut olarak aşağıdaki gibi 4 adımda tanımlamak mümkündür.
Problem Tanımlama
Veri Hazırlama
Model/Algoritma Seçimi
Sonuçları İyileştirme

In [ ]:
NumPy Kütüphanesi
Numpy kütüphanesi adını Sayısal Python (Numerical Python) kelimelerinin kısaltmalarından almıştır.
Kütüphanenin en önemli özelliği, hızlı matematiksel işlemler yapılabilecek diziler (array) sunmasıdır.
Python’un kendi veri yapısında bulunan liste veri yapısına göre oldukça hızlı çalışan Numpy 
kütüphanesi kullanılarak; rastgele sayı üretme, matris çarpımı ve doğrusal cebir işlemleri gibi
birçok matematiksel işlemi gerçekleştirmek mümkündür. Kütüphane kullanımına yönelik; çok boyutlu
dizi oluşturma, dizilerin farkını/toplamını/çarpımını hesaplama, belirli bir değerden büyük olan
elemanların indislerini bularak elemanları ekranı yazdırma gibi örnekler aşağıda gösterilmiştir.

In [1]:
import numpy as np

#Dizi oluşturma
d1 = np.array([5.5,9,10])
d2 = np.array([(3.5,8,11), (4,7,9), (2,2,1.1)], dtype=float)

#Fark alma 1. Yöntem
d3 = d2 - d1
print("Fark 1 / d3 --> ", d3)

#Fark alma 2. Yöntem
d3 = np.subtract(d1, d2) 
print("Fark 2 / d3 --> ", d3)

#d1 ve d2'yi toplayıp d1 üzerine yazma
d1 = d1 + d2
print("Toplam d1 --> ", d1)

#Değeri 3'ten büyük elemanların indislerini bul
sonuc = d1 > 3

#Bulunan indisleri kullanarak, elemanları ekranra yazdır
print("3'ten büyük elemanlar -->", d1[sonuc])

#İki matrisin çarpımı
d4 = np.dot(d1, d2)
print("Çarpım d4:", d4)

#Matristen 1.sütunu çıkartma
d4 = np.delete(d4,0,1)
print("Çıkartma d4:", d4)

Fark 1 / d3 -->  [[-2.  -1.   1. ]
 [-1.5 -2.  -1. ]
 [-3.5 -7.  -8.9]]
Fark 2 / d3 -->  [[ 2.   1.  -1. ]
 [ 1.5  2.   1. ]
 [ 3.5  7.   8.9]]
Toplam d1 -->  [[ 9.  17.  21. ]
 [ 9.5 16.  19. ]
 [ 7.5 11.  11.1]]
3'ten büyük elemanlar --> [ 9.  17.  21.   9.5 16.  19.   7.5 11.  11.1]
Çarpım d4: [[141.5  233.   275.1 ]
 [135.25 226.   269.4 ]
 [ 92.45 159.2  193.71]]
Çıkartma d4: [[233.   275.1 ]
 [226.   269.4 ]
 [159.2  193.71]]


In [2]:
#Dizideki en küçük eleman bulma
print("d4 min:", np.min(d4))

#Dizideki en büyük eleman bulma
print("d4 max:", np.max(d4))

#Dizinin ortalamasını alma
print("d4 ortalama:", d4.mean())

#Dizinin toplamını bulma
print("d4 toplam:", d4.sum())

#Karekök alma
print("d4 karekök-->", np.sqrt(d4))

#Dizinin logaritmasını hesaplama
print("d4 logaritma-->", np.log(d4))

#Tranpoz alma
print("d4 transpoz:", np.transpose(d4))

d4 min: 159.2
d4 max: 275.1
d4 ortalama: 226.06833333333336
d4 toplam: 1356.41
d4 karekök--> [[15.26433752 16.58613879]
 [15.03329638 16.41340915]
 [12.61744824 13.91797399]]
d4 logaritma--> [[5.45103845 5.61713467]
 [5.420535   5.59619726]
 [5.07016127 5.2663622 ]]
d4 transpoz: [[233.   226.   159.2 ]
 [275.1  269.4  193.71]]
