In [37]:
import numpy as np
import pandas as pd

## **NUMPY**

#### **Making a Numpy Array** (From the list, Arrange, Zeros, Ones, Linspace, Random)
#### **Methods with Nump Arrays**  
#### **Indexing & Slicing**   
#### **Conditional Selection**   
#### **Numpy Operations**

#### **Making a Numpy Array**

##### -From the list

In [43]:
my_list =[1,2,3,5,6,7]
arr =np.array(my_list)
arr

array([1, 2, 3, 5, 6, 7])

In [40]:
my_list_matrix = [[1,2,3],[4,5,6],[7,8,9]]
arr_2 =np.array(my_list_matrix)
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
type(my_list_matrix)

list

In [42]:
type(arr_2)

numpy.ndarray

#### -Arange ile Numpy Array olusturma

In [44]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### -Zeros ile Numpy Array olusturma

In [45]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### -Ones ile Numpy Array olusturma

In [48]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

#### -Linspace ile Numpy Array olusturma

In [50]:
# Gives us evenly space between start and stop(inclusive)  numbers by given number. In our example we want 4 linearly spaced even number
np.linspace(0,10,4)


array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

#### -Random ile Numpy Array olusturma

In [58]:
# np.random.rand --> Gives us random numbers between given row and column number.

np.random.rand(4,5)

array([[0.75058743, 0.88768814, 0.20483053, 0.22687686, 0.81117673],
       [0.83049492, 0.12771545, 0.46681086, 0.04172496, 0.46234585],
       [0.61214403, 0.09586517, 0.17003142, 0.5379505 , 0.12611273],
       [0.29707441, 0.04531902, 0.21250546, 0.33461042, 0.3142416 ]])

In [60]:
# np.random.randn --> Gives us a number in the normal distribution, for that number mostly close to 0

np.random.randn(2,3)

array([[-1.54359636,  0.30415957, -1.1617678 ],
       [-1.07223594,  1.04487084,  1.4021763 ]])

In [64]:
# np.random.randint --> Gives us randomly chosen integer between the given numbers, stop is exclusive by requested number

np.random.randint (0,101,7)

array([18,  1, 54, 33, 51, 66, 12])

In [62]:
# Same logic, but this time gives us 4 by 5 array with random numbers

np.random.randint (0,101,(4,5))

array([[15, 50, 89, 85, 54],
       [98, 59, 70, 86, 83],
       [21, 27, 19, 60, 79],
       [71,  9, 66, 37, 66]])

In [65]:
# np.random.seed --> If we want to get same random set we use seed  with the random number in the same jupyter cell

np.random.seed (101)
np.random.randint(0,101,12)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40,  4, 63])

In [66]:
np.random.seed (101)
np.random.randint(0,101,12)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40,  4, 63])

### **Methods with Numpy Arrays**

#### **reshape**

In [67]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr.shape

(25,)

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### **max** , **min**, **argmax**, **argmin**

In [70]:
arr = np.random.randint(0,55,15)
arr

array([40, 53, 28,  0, 46,  5, 12, 29, 40, 49, 19, 47,  8, 51, 29])

In [71]:
# max
arr.max()

53

In [72]:
# min
arr.min()

0

In [73]:
# argmax
arr.argmax()

1

In [75]:
# argmin
arr.argmin()

3

#### **dtype**,  **shape**

In [76]:
# dtype
arr.dtype

dtype('int64')

In [77]:
# shape
arr.shape

(15,)

### **Indexing** & **Slicing**

In [78]:
arr = np.random.randint(0,55,15)
arr

array([51, 34, 44,  8, 19, 10, 12, 31, 43, 23,  0, 41,  9, 47,  8])

In [79]:
arr[4:10]

array([19, 10, 12, 31, 43, 23])

In [80]:
arr_2= arr.reshape(3,5)
arr_2

array([[51, 34, 44,  8, 19],
       [10, 12, 31, 43, 23],
       [ 0, 41,  9, 47,  8]])

In [82]:
arr_2[1:,1:3]

array([[12, 31],
       [41,  9]])

In [81]:
arr_2[1,3]

43

##### **Broadcasting**

In [87]:
arr_2[:2,2:4]=100
arr_2

array([[ 51,  34, 100, 100,  19],
       [ 10,  12, 100, 100,  23],
       [  0,  41,   9,  47,   8]])

### **Conditional Selection**

In [88]:
arr = np.random.randint(0,55,15)
arr

array([36, 19, 35, 28,  7, 10, 52, 39, 38, 46,  9, 52, 18,  7, 39])

In [89]:
arr[arr>18]

array([36, 19, 35, 28, 52, 39, 38, 46, 52, 39])

In [90]:
arr>18

array([ True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False, False,  True])

### **Numpy Operations**

In [91]:
arr

array([36, 19, 35, 28,  7, 10, 52, 39, 38, 46,  9, 52, 18,  7, 39])

In [92]:
# +
arr + 5

array([41, 24, 40, 33, 12, 15, 57, 44, 43, 51, 14, 57, 23, 12, 44])

In [93]:
# *
arr * 3

array([108,  57, 105,  84,  21,  30, 156, 117, 114, 138,  27, 156,  54,
        21, 117])

In [94]:
# /
arr/2

array([18. ,  9.5, 17.5, 14. ,  3.5,  5. , 26. , 19.5, 19. , 23. ,  4.5,
       26. ,  9. ,  3.5, 19.5])

In [95]:
# sum
arr.sum()

435

In [102]:
# mean
x = arr.mean()
x

29.0

In [104]:
arr[arr>arr.mean()]

array([36, 35, 52, 39, 38, 46, 52, 39])

In [97]:
# std
arr.std()

15.629032812898778

In [98]:
# Operations with two dimesnional array in Numpy
arr_2


array([[ 51,  34, 100, 100,  19],
       [ 10,  12, 100, 100,  23],
       [  0,  41,   9,  47,   8]])

In [105]:
# sum
arr_2.sum(axis=0)

array([ 61,  87, 209, 247,  50])

In [106]:
arr_2.sum(axis=1)

array([304, 245, 105])

In [107]:
arr_2[0,0]+arr_2[1,0]+arr_2[2,0]

61

In [108]:
arr_2[0,0]+arr_2[0,1]+arr_2[0,2]+arr_2[0,3]+arr_2[0,4]

304

#### Reading From CSV

In [109]:
#read_csv

df = pd.read_csv('world-happiness-report-2021.csv')

#### **df.shape**    --> Gives up how many rows and columns in the dataframe (df)
#### **df.head()**   --> Gives us top 5 or if we specify number, that number of rows.
#### **df.tail()**   --> Gives us bottom 5 or if we specify number, that number of rows.
#### **df.info()**   --> Gives us number of rows and columns and all the data types in the columns as well.
#### **df.describe()**--> Gives us some basic statistical details(such as; mean, std, percentiles).
#### **df.columns**  --> Gives us column names in the df.

In [110]:
# shape
df.shape

(149, 20)

In [113]:
# head
df.head()

Country name Regional indicator  Ladder score  \
0      Finland     Western Europe         7.842   
1      Denmark     Western Europe         7.620   
2  Switzerland     Western Europe         7.571   
3      Iceland     Western Europe         7.554   
4  Netherlands     Western Europe         7.464   

   Standard error of ladder score  upperwhisker  lowerwhisker  \
0                           0.032         7.904         7.780   
1                           0.035         7.687         7.552   
2                           0.036         7.643         7.500   
3                           0.059         7.670         7.438   
4                           0.027         7.518         7.410   

   Logged GDP per capita  Social support  Healthy life expectancy  \
0                 10.775           0.954                     72.0   
1                 10.933           0.954                     72.7   
2                 11.117           0.942                     74.4   
3                 10.878           0.983                     73.0   
4                 10.932           0.942                     72.4   

   Freedom to make life choices  Generosity  Perceptions of corruption  \
0                         0.949      -0.098                      0.186   
1                         0.946       0.030                      0.179   
2                         0.919       0.025                      0.292   
3                         0.955       0.160                      0.673   
4                         0.913       0.175                      0.338   

   Ladder score in Dystopia  Explained by: Log GDP per capita  \
0                      2.43                             1.446   
1                      2.43                             1.502   
2                      2.43                             1.566   
3                      2.43                             1.482   
4                      2.43                             1.501   

   Explained by: Social support  Explained by: Healthy life expectancy  \
0                         1.106                                  0.741   
1                         1.108                                  0.763   
2                         1.079                                  0.816   
3                         1.172                                  0.772   
4                         1.079                                  0.753   

   Explained by: Freedom to make life choices  Explained by: Generosity  \
0                                       0.691                     0.124   
1                                       0.686                     0.208   
2                                       0.653                     0.204   
3                                       0.698                     0.293   
4                                       0.647                     0.302   

   Explained by: Perceptions of corruption  Dystopia + residual  
0                                    0.481                3.253  
1                                    0.485                2.868  
2                                    0.413                2.839  
3                                    0.170                2.967  
4                                    0.384                2.798

In [114]:
df.sample(3)

Country name           Regional indicator  Ladder score  \
62          Peru  Latin America and Caribbean         5.840   
139      Burundi           Sub-Saharan Africa         3.775   
59       Croatia   Central and Eastern Europe         5.882   

     Standard error of ladder score  upperwhisker  lowerwhisker  \
62                            0.075         5.988         5.692   
139                           0.107         3.985         3.565   
59                            0.048         5.975         5.788   

     Logged GDP per capita  Social support  Healthy life expectancy  \
62                   9.458           0.832                   68.250   
139                  6.635           0.490                   53.400   
59                  10.217           0.924                   70.799   

     Freedom to make life choices  Generosity  Perceptions of corruption  \
62                          0.822      -0.154                      0.891   
139                         0.626      -0.024                      0.607   
59                          0.754      -0.118                      0.939   

     Ladder score in Dystopia  Explained by: Log GDP per capita  \
62                       2.43                             0.986   
139                      2.43                             0.000   
59                       2.43                             1.251   

     Explained by: Social support  Explained by: Healthy life expectancy  \
62                          0.833                                  0.623   
139                         0.062                                  0.155   
59                          1.039                                  0.703   

     Explained by: Freedom to make life choices  Explained by: Generosity  \
62                                        0.536                     0.087   
139                                       0.298                     0.172   
59                                        0.453                     0.111   

     Explained by: Perceptions of corruption  Dystopia + residual  
62                                     0.031                2.744  
139                                    0.212                2.876  
59                                     0.000                2.325

In [115]:
# tail
df.tail()

Country name  Regional indicator  Ladder score  \
144      Lesotho  Sub-Saharan Africa         3.512   
145     Botswana  Sub-Saharan Africa         3.467   
146       Rwanda  Sub-Saharan Africa         3.415   
147     Zimbabwe  Sub-Saharan Africa         3.145   
148  Afghanistan          South Asia         2.523   

     Standard error of ladder score  upperwhisker  lowerwhisker  \
144                           0.120         3.748         3.276   
145                           0.074         3.611         3.322   
146                           0.068         3.548         3.282   
147                           0.058         3.259         3.030   
148                           0.038         2.596         2.449   

     Logged GDP per capita  Social support  Healthy life expectancy  \
144                  7.926           0.787                   48.700   
145                  9.782           0.784                   59.269   
146                  7.676           0.552                   61.400   
147                  7.943           0.750                   56.201   
148                  7.695           0.463                   52.493   

     Freedom to make life choices  Generosity  Perceptions of corruption  \
144                         0.715      -0.131                      0.915   
145                         0.824      -0.246                      0.801   
146                         0.897       0.061                      0.167   
147                         0.677      -0.047                      0.821   
148                         0.382      -0.102                      0.924   

     Ladder score in Dystopia  Explained by: Log GDP per capita  \
144                      2.43                             0.451   
145                      2.43                             1.099   
146                      2.43                             0.364   
147                      2.43                             0.457   
148                      2.43                             0.370   

     Explained by: Social support  Explained by: Healthy life expectancy  \
144                         0.731                                  0.007   
145                         0.724                                  0.340   
146                         0.202                                  0.407   
147                         0.649                                  0.243   
148                         0.000                                  0.126   

     Explained by: Freedom to make life choices  Explained by: Generosity  \
144                                       0.405                     0.103   
145                                       0.539                     0.027   
146                                       0.627                     0.227   
147                                       0.359                     0.157   
148                                       0.000                     0.122   

     Explained by: Perceptions of corruption  Dystopia + residual  
144                                    0.015                1.800  
145                                    0.088                0.648  
146                                    0.493                1.095  
147                                    0.075                1.205  
148                                    0.010                1.895

In [117]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   Country name                                149 non-null    object 
 1   Regional indicator                          149 non-null    object 
 2   Ladder score                                149 non-null    float64
 3   Standard error of ladder score              149 non-null    float64
 4   upperwhisker                                149 non-null    float64
 5   lowerwhisker                                149 non-null    float64
 6   Logged GDP per capita                       149 non-null    float64
 7   Social support                              149 non-null    float64
 8   Healthy life expectancy                     149 non-null    float64
 9   Freedom to make life choices                149 non-null    float64
 10  Generosity    

In [119]:
# describe
df.describe()

Ladder score  Standard error of ladder score  upperwhisker  \
count    149.000000                      149.000000    149.000000   
mean       5.532839                        0.058752      5.648007   
std        1.073924                        0.022001      1.054330   
min        2.523000                        0.026000      2.596000   
25%        4.852000                        0.043000      4.991000   
50%        5.534000                        0.054000      5.625000   
75%        6.255000                        0.070000      6.344000   
max        7.842000                        0.173000      7.904000   

       lowerwhisker  Logged GDP per capita  Social support  \
count    149.000000             149.000000      149.000000   
mean       5.417631               9.432208        0.814745   
std        1.094879               1.158601        0.114889   
min        2.449000               6.635000        0.463000   
25%        4.706000               8.541000        0.750000   
50%        5.413000               9.569000        0.832000   
75%        6.128000              10.421000        0.905000   
max        7.780000              11.647000        0.983000   

       Healthy life expectancy  Freedom to make life choices  Generosity  \
count               149.000000                    149.000000  149.000000   
mean                 64.992799                      0.791597   -0.015134   
std                   6.762043                      0.113332    0.150657   
min                  48.478000                      0.382000   -0.288000   
25%                  59.802000                      0.718000   -0.126000   
50%                  66.603000                      0.804000   -0.036000   
75%                  69.600000                      0.877000    0.079000   
max                  76.953000                      0.970000    0.542000   

       Perceptions of corruption  Ladder score in Dystopia  \
count                 149.000000                    149.00   
mean                    0.727450                      2.43   
std                     0.179226                      0.00   
min                     0.082000                      2.43   
25%                     0.667000                      2.43   
50%                     0.781000                      2.43   
75%                     0.845000                      2.43   
max                     0.939000                      2.43   

       Explained by: Log GDP per capita  Explained by: Social support  \
count                        149.000000                    149.000000   
mean                           0.977161                      0.793315   
std                            0.404740                      0.258871   
min                            0.000000                      0.000000   
25%                            0.666000                      0.647000   
50%                            1.025000                      0.832000   
75%                            1.323000                      0.996000   
max                            1.751000                      1.172000   

       Explained by: Healthy life expectancy  \
count                             149.000000   
mean                                0.520161   
std                                 0.213019   
min                                 0.000000   
25%                                 0.357000   
50%                                 0.571000   
75%                                 0.665000   
max                                 0.897000   

       Explained by: Freedom to make life choices  Explained by: Generosity  \
count                                  149.000000                149.000000   
mean                                     0.498711                  0.178047   
std                                      0.137888                  0.098270   
min                                      0.000000                  0.000000   
25%                                      0.409000                  0.105000   
50%              

In [120]:
# columns
df.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')