In [1]:
import numpy as np

In [4]:
liste = [1,2,3,4,5,6,7,8]
a = np.array(liste)
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
type(a)  # değişkeninin tipini aldık

numpy.ndarray

In [8]:
a.dtype  # dizinin tuttuğu değerlerin tipini aldık. Hepsi aynı tip veri


dtype('int32')

In [9]:
a.shape  # tek boyutlu olduğu için bu dizi bir vektör

(8,)

In [11]:
a[2] = 8 # değer ataması yaptık. 
a

array([1, 2, 8, 4, 5, 6, 7, 8])

In [14]:
b = np.array([[1,2,3], [6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [13]:
b.shape

(2, 3)

In [17]:
b[1,1] = 0  # matrise değer ataması yaptık. 
b

array([[1, 2, 3],
       [6, 0, 8]])

In [20]:
c = np.arange(1,10).reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
c[1,1]  

5

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
np.full((2,2),-1)  # 2'e 2 -1 doldurduk

array([[-1, -1],
       [-1, -1]])

In [35]:
np.empty((3,3))  # sıfıra çok yakın sayılardan 3X3 doldurduk.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.eye(4)  # 4x4 çarpaz değerler oluşturdu

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.linspace(2,30,5)  # belirtilen aralıklarda eşit sayıda istenilen kadar böler

array([ 2.,  9., 16., 23., 30.])

In [38]:
np.random.random((3,3))  # sıfır ile bir arasında 3x3 


array([[0.69592308, 0.33086448, 0.32212976],
       [0.53475601, 0.89297563, 0.53902118],
       [0.05177651, 0.79575723, 0.77091336]])

In [40]:
np.random.randint(5,10, size = (3,3))  

array([[9, 6, 6],
       [7, 9, 5],
       [7, 9, 5]])

In [41]:
z = np.random.randint(2,15, size = (5,3))

In [42]:
z.shape

(5, 3)

In [43]:
z.reshape(3,5)

array([[ 6,  6, 13,  5, 12],
       [ 2, 13,  3,  8,  3],
       [ 7, 13, 12, 11,  9]])

In [44]:
z.ravel()  #  flatting düzleştirme işlemi yapılıor. 

array([ 6,  6, 13,  5, 12,  2, 13,  3,  8,  3,  7, 13, 12, 11,  9])

In [46]:
z = z.ravel()

In [51]:
[z.max(),z.min()]

[13, 2]

In [52]:
z.argmax()  # en büyük değerin index i

2

### Stacking 

In [54]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3], [7,9]])

In [55]:
a

array([[1, 2],
       [3, 4]])

In [56]:
b

array([[-1,  3],
       [ 7,  9]])

In [59]:
np.hstack((a,b))

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [60]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [62]:
dizi = np.arange(0,10).reshape(5,2)
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
dizi_1 = np.arange(3,13).reshape(5,2)

In [64]:
np.concatenate([dizi, dizi_1], axis= 1)

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [70]:
array_1 = np.arange(1,13).reshape(3,4)
arrray_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
array_1[:2,1:3]

array([[2, 3],
       [6, 7]])

In [72]:
array_2 = array_1.copy()

In [73]:
array_2[1,1]

6

### filtreleme

In [76]:
m = np.arange(1,13).reshape(4,3)
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
ikiden_büyük = m>2
ikiden_büyük


array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
ikiden_büyük = m[m>2]
ikiden_büyük

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [84]:
y = np.arange(5,9).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [85]:
x-y

array([[-4, -4],
       [-4, -4]])

In [86]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [87]:
x*y

array([[ 5, 12],
       [21, 32]])

In [88]:
np.dot(x,y)  # dot product matris matris çarpım

array([[19, 22],
       [43, 50]])

In [89]:
x@y  # .dot ile aynı

array([[19, 22],
       [43, 50]])

In [90]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [91]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [92]:
np.square(x,y)

array([[ 1,  4],
       [ 9, 16]])

In [93]:
np.exp(3)  # e^3 e = 2,71

20.085536923187668

In [96]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])
t

array([0.52359878, 1.57079633, 1.04719755])