In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
0-D Arrays


SyntaxError: invalid syntax (<ipython-input-6-edb8dfdd8083>, line 1)

In [ ]:
a = np.array(55)
a

In [ ]:
1-D Arrays


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

In [ ]:
# boyut ayarlamak için ndmin() kullanılır

In [ ]:
a = np.array([1,2,3], ndmin= 5)
a.ndim

In [ ]:
arr = np.array([1, 2, 3, 4])
bar = np.array([5, 6, 7, 8])
c = np.concatenate([arr,bar])

print(c)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

In [ ]:
print(arr[1, 1, 2])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

In [ ]:
print(arr[0:2, 2])


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

In [ ]:
print(arr[0:2, 1:4])

In [ ]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr

In [ ]:
arr[1:5:2]

In [ ]:
a = np.array(["a","b","c","d","e","f"])
a

In [ ]:
a.dtype

In [ ]:
arr = np.array(['apple', 'bananaaaaa', 'cherry'],dtype = "U")
arr.dtype

In [ ]:
arr = np.array(['1', '2', 3], dtype='i')
arr

In [ ]:
arr = np.array(['a', '2', 3], dtype='i')


In [ ]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = np.array(arr,dtype= "str")
new_arr

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype(int)
new_arr

In [ ]:
arr = np.array([1, 0, 3])
new_arr = arr.astype("bool")
new_arr

In [ ]:
new_arr_2 = np.array(arr,dtype="bool")
new_arr_2

In [ ]:
arr = []

### numpy copy

In [ ]:
arr = np.array([1,2,4,5])
x = arr
arr[0] = 10
x  #  orijinal listede yapılan değişiklikler kopya edilen listeyi de etkiledi

In [ ]:
# orijinal verilerin de etkilenmesini önlemek için copy() kullanılır. 
arr = np.arange(2,20).reshape(6,3)
x = arr.copy()
arr[0,0] = 1000

In [ ]:
arr

In [ ]:
x  # kopya liste etkilenmedi

### Check if Array Owns it's Data
değişkenlerin kendi verisini mi yoksa bir başka verinin kopyasını taşıdğını kontrol edelim.
Bunun için base etiketi kullanılır.
eğer arr.base None değeri döndürüyorsa değişken kendi data değerini taşıyor. eğer bir değer döndürüyorsa başka bir değişkenin değerini taşıyo demektir.



In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

In [ ]:
print(x.base)  # kendi datasını taşıyor. 

In [ ]:
y

### NumPy Array Shape
The shape of an array is the number of elements in each dimension.



In [ ]:
# shape etiketi ile dizinin sahip olduğu satır ve sütün sayılarını görebiliriz
# shape bir tuple değeri döndürür

In [ ]:
a = np.arange(2,10).reshape(4,2)
a.shape

In [ ]:
a

In [ ]:
a = np.array([1,2,3,4],ndmin = 5)
a

In [ ]:
a.shape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(-1)
arr.shape

### Reshape From 1-D to 2-D


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

In [ ]:
arr.reshape(4,3)


In [ ]:
new_arr = arr.reshape(2,3,2) # önce tüm listeyi ikiye böldü. Sonra iki parçayı kendi için de 3x2 yaptı
new_arr

In [ ]:
new_arr[:,1,0]

Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
arr = np.random.randint(2,8, size = (3,3))
arr

In [ ]:
new_arr = arr.reshape(-1)
new_arr


In [ ]:
for i in new_arr:
    print(i)

In [ ]:
arr = np.arange(2,20).reshape(6,3)
arr

In [ ]:
for i in arr:
    for j in i:
        print(j)

In [ ]:
Iterating Arrays Using nditer()


In [ ]:
arr = np.arange(2,20).reshape(2,3,3)
arr.dtype

In [ ]:
for i in np.nditer(arr):  # ne kadar iç içe gelmiş liste olsa da hepsini yazdırabiliyoruz
    print(i)

In [ ]:
arr = np.arange(2,10)
arr

In [7]:
np.random.seed() # rastgele oluşturulan değerlerin sabit olarak kalmasını sağlıyor. her çalıştırmada değişmesini engelliyor. 
populasyon = np.random.randint(10,80, size = 10000)

In [8]:
orneklem = np.random.choice(populasyon, size = 100)

In [10]:
populasyon.mean()

44.4555

In [11]:
orneklem.mean()

55.7

In [35]:
orneklem1 = np.random.choice(populasyon, size = 100)
orneklem2 = np.random.choice(populasyon, size = 100)
orneklem3 = np.random.choice(populasyon, size = 100)
orneklem4 = np.random.choice(populasyon, size = 100)
orneklem5 = np.random.choice(populasyon, size = 100)


In [36]:
orneklem1.mean()

43.44

In [29]:
orneklem2.mean()

43.76

In [32]:
orneklem3.mean()

43.14

In [34]:
orneklem4.mean()

43.41

In [33]:
orneklem5.mean()

45.14