In [1]:
import numpy as np

In [46]:
a=[1,3,5,7]
b=[2,4,6,8]
c=[3,6,9,12]
a=np.array(a)
b=np.array(b)
c=np.array(c)
d=a+b+c
d=list(d)
print(d)

[6, 13, 20, 27]


In [3]:
d=np.array([3.14,14,15,16])

In [4]:
type(d)

numpy.ndarray

In [5]:
d.dtype

dtype('float64')

In [7]:
d

array([ 3.14, 14.  , 15.  , 16.  ])

In [10]:
np.array([2,4,6,8], dtype=str)

array(['2', '4', '6', '8'], dtype='<U1')

In [11]:
np.array([2,4,6], dtype=int)

array([2, 4, 6])

In [12]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [14]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

In [15]:
np.random.randint(3,6, size=5)

array([4, 5, 3, 5, 5])

In [16]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [17]:
np.arange(5,10,2)

array([5, 7, 9])

In [23]:
np.arange(4,20).reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
np.random.randint(3,9, size=(2,4))

array([[6, 7, 6, 8],
       [7, 3, 5, 4]])

In [29]:
a=np.arange(1,16,2)

In [30]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [31]:
a.reshape(2,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [32]:
# concate:

In [33]:
a=np.random.randint(1,6,size=5)
b=np.random.randint(2,7, size=5)

In [34]:
a

array([1, 4, 1, 4, 4])

In [35]:
b

array([4, 3, 2, 2, 6])

In [37]:
c=np.concatenate([a,b])
c

array([1, 4, 1, 4, 4, 4, 3, 2, 2, 6])

In [38]:
type(c)

numpy.ndarray

In [41]:
a= np.random.randint(2,7,size=4)
b=np.random.randint(10,14,size=6)

In [43]:
c=np.concatenate([a,b])

In [44]:
c

array([ 6,  5,  3,  4, 13, 11, 12, 12, 13, 11])

In [45]:
a=np.random.randint(2,7,size=(3,4))
b= np.random.randint(8,14,size=(3,4))
c=np.concatenate([a,b])
c

array([[ 2,  5,  2,  2],
       [ 2,  4,  6,  3],
       [ 6,  5,  6,  5],
       [12,  8,  9, 12],
       [13, 11,  9,  8],
       [ 8,  9, 10, 12]])

In [71]:
a=np.random.randint(3,9,size=(3,4))
a

array([[8, 6, 6, 4],
       [5, 4, 5, 3],
       [5, 4, 3, 6]])

In [72]:
b=np.random.randint(5,15,size=(3,4))
b

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [75]:
c=np.concatenate([a,b],axis=1)
c

array([[ 8,  6,  6,  4, 13,  5, 10, 13],
       [ 5,  4,  5,  3,  6, 11,  6,  8],
       [ 5,  4,  3,  6,  6, 13, 12, 10]])

In [70]:
c=np.concatenate([a,b],axis=0)
c

array([[ 6,  7,  6,  5,  5,  3],
       [ 4,  4,  5,  5,  5,  6],
       [ 9,  9,  5,  7, 13, 12],
       [12, 11,  8, 10, 13,  5],
       [12,  8, 11, 11, 13, 14]])

In [53]:
c=np.concatenate([a,b], axis=0)
c

array([[ 5,  6,  5,  6],
       [ 8,  4,  7,  8],
       [ 7,  8,  5,  3],
       [11,  6,  5, 14],
       [11,  9,  5, 12],
       [ 8, 10,  5, 11]])

In [64]:
# satırları aynı olan axis=1
a=np.random.randint(3,9,size=(3,3))
b=np.random.randint(5,15,size=(3,6))

In [67]:
c=np.concatenate([a,b], axis=1)
c

array([[ 4,  4,  6, 13,  6, 12, 10, 11,  7],
       [ 7,  6,  5, 10,  7,  5, 11, 14, 13],
       [ 4,  5,  7,  5, 10,  9,  7,  8,  6]])

In [68]:
# axis=0 yani sutunu eşit olan.
a=np.random.randint(3,9,size=(2,6))
b=np.random.randint(5,15,size=(3,6))

In [69]:
c=np.concatenate([a,b], axis=0)
c

array([[ 6,  7,  6,  5,  5,  3],
       [ 4,  4,  5,  5,  5,  6],
       [ 9,  9,  5,  7, 13, 12],
       [12, 11,  8, 10, 13,  5],
       [12,  8, 11, 11, 13, 14]])

In [77]:
c.ndim

2

In [78]:
c.size

24

In [80]:
c.shape

(3, 8)

In [82]:
c.mean()

7.166666666666667

In [83]:
c.std()

3.223179934302286

In [84]:
c.var()

10.38888888888889

In [90]:
c

array([[ 8,  6,  6,  4, 13,  5, 10, 13],
       [ 5,  4,  5,  3,  6, 11,  6,  8],
       [ 5,  4,  3,  6,  6, 13, 12, 10]])

In [97]:
c

array([[ 8,  6,  6,  4, 13,  5, 10, 13],
       [ 5,  4,  5,  3,  6, 11,  6,  8],
       [ 5,  4,  3,  6,  6, 13, 12, 10]])

In [94]:
np.sort(c, axis=1)
# sort değerinde axis=1 satır olarak sıralar.
# sort fonksiyonunda axis=1 default değer.

array([[ 4,  5,  6,  6,  8, 10, 13, 13],
       [ 3,  4,  5,  5,  6,  6,  8, 11],
       [ 3,  4,  5,  6,  6, 10, 12, 13]])

In [98]:
np.sort(c, axis=0)
# axis=0 dersek sutun bazında sıralar.

array([[ 5,  4,  3,  3,  6,  5,  6,  8],
       [ 5,  4,  5,  4,  6, 11, 10, 10],
       [ 8,  6,  6,  6, 13, 13, 12, 13]])

In [99]:
np.sort(c)

array([[ 4,  5,  6,  6,  8, 10, 13, 13],
       [ 3,  4,  5,  5,  6,  6,  8, 11],
       [ 3,  4,  5,  6,  6, 10, 12, 13]])

In [100]:
c

array([[ 8,  6,  6,  4, 13,  5, 10, 13],
       [ 5,  4,  5,  3,  6, 11,  6,  8],
       [ 5,  4,  3,  6,  6, 13, 12, 10]])

In [106]:
a

array([[8, 6, 6, 4],
       [5, 4, 5, 3],
       [5, 4, 3, 6]])

In [107]:
a[0]

array([8, 6, 6, 4])

In [108]:
a[1]

array([5, 4, 5, 3])

In [104]:
a[2]

array([5, 4, 3, 6])

In [105]:
a[-1]

array([5, 4, 3, 6])

In [109]:
a

array([[8, 6, 6, 4],
       [5, 4, 5, 3],
       [5, 4, 3, 6]])

In [110]:
a[1,1] 

4

In [111]:
a[1][1]

4

In [112]:
a[0:3,2]

array([6, 5, 3])

In [114]:
a[0:2,1:3]

array([[6, 6],
       [4, 5]])

In [115]:
a

array([[8, 6, 6, 4],
       [5, 4, 5, 3],
       [5, 4, 3, 6]])

In [116]:
a[0]

array([8, 6, 6, 4])

In [117]:
a[1,1]

4

In [118]:
a[0:3,2:4]

array([[6, 4],
       [5, 3],
       [3, 6]])

In [119]:
a[1:3,0:2]

array([[5, 4],
       [5, 4]])

In [120]:
a=np.copy(b)

In [121]:
b

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [123]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [124]:
d=np.copy(b)

In [125]:
b[2,2]=3

In [126]:
b

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13,  3, 10]])

In [127]:
d

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [128]:
d[1,1]=1

In [129]:
d

array([[13,  5, 10, 13],
       [ 6,  1,  6,  8],
       [ 6, 13, 12, 10]])

In [130]:
b

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13,  3, 10]])

In [131]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [132]:
a>12

array([[ True, False, False,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [133]:
a[a>11]

array([13, 13, 13, 12])

In [134]:
a[a>10]

array([13, 13, 11, 13, 12])

In [135]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [136]:
len(a[a>12])

3

In [142]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [143]:
a[0:2]>7

array([[ True, False,  True,  True],
       [False,  True, False,  True]])

In [150]:
# Ufunc:

In [151]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [153]:
np.add(a,13) # add fonksiyonu toplama

array([[26, 18, 23, 26],
       [19, 24, 19, 21],
       [19, 26, 25, 23]])

In [154]:
np.subtract(a,5)

array([[8, 0, 5, 8],
       [1, 6, 1, 3],
       [1, 8, 7, 5]])

In [155]:
np.multiply(a,3)

array([[39, 15, 30, 39],
       [18, 33, 18, 24],
       [18, 39, 36, 30]])

In [158]:
np.divide(a,2)

array([[6.5, 2.5, 5. , 6.5],
       [3. , 5.5, 3. , 4. ],
       [3. , 6.5, 6. , 5. ]])

In [159]:
np.mod(a,3)

array([[1, 2, 1, 1],
       [0, 2, 0, 2],
       [0, 1, 0, 1]], dtype=int32)

In [160]:
np.absolute(a) # mutlak.

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])

In [161]:
np.cos(a[1])

array([ 0.96017029,  0.0044257 ,  0.96017029, -0.14550003])

In [162]:
np.sin(a[2])

array([-0.2794155 ,  0.42016704, -0.53657292, -0.54402111])

In [163]:
np.tan(a)

array([[   0.46302113,   -3.38051501,    0.64836083,    0.46302113],
       [  -0.29100619, -225.95084645,   -0.29100619,   -6.79971146],
       [  -0.29100619,    0.46302113,   -0.63585993,    0.64836083]])

In [165]:
np.log(a[1,2])

1.791759469228055

In [166]:
np.log10(a[1])

array([0.77815125, 1.04139269, 0.77815125, 0.90308999])

In [167]:
np.sqrt(16)

4.0

In [169]:
np.power(4,2)

16

In [172]:
np.power(a,a)

array([[-1692154371,        3125,  1410065408, -1692154371],
       [      46656,  1843829075,       46656,    16777216],
       [      46656, -1692154371,  -251658240,  1410065408]], dtype=int32)

In [173]:
a

array([[13,  5, 10, 13],
       [ 6, 11,  6,  8],
       [ 6, 13, 12, 10]])