In [2]:
import numpy as np

In [3]:
a = [1,3,5,7]
b = [2,4,6,8]
c = [3,6,9,12]
a = np.array(a)
b = np.array(b)
c = np.array(c)
d = a*b*c
d = list(d)
print(d)

[6, 72, 270, 672]


In [4]:
d = np.array([3.14,14,15,16])
type(d)

numpy.ndarray

In [6]:
d.dtype

dtype('float64')

In [7]:
np.array([2,4,6,8], dtype= str)

array(['2', '4', '6', '8'], dtype='<U1')

In [8]:
np.array([2,4,6,8],dtype = int)

array([2, 4, 6, 8])

In [9]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [10]:
np.ones(6,dtype= int)

array([1, 1, 1, 1, 1, 1])

In [19]:
np.random.randint(3,6, size = 5)

array([5, 4, 3, 4, 5])

In [20]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(5,10,2)

array([5, 7, 9])

### iki boyutlu

In [23]:
np.arange(3,13).reshape(2,5)

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [24]:
np.arange(3,13).reshape(5,2)

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [25]:
np.arange(4,20).reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
np.arange(4,20).reshape(8,2)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [28]:
np.random.randint(3,9, size = (2,4))

array([[8, 6, 8, 3],
       [6, 4, 4, 7]])

In [31]:
np.random.randint(2,8, size = (3,6))

array([[4, 7, 4, 5, 2, 5],
       [7, 4, 3, 2, 6, 6],
       [3, 7, 5, 6, 6, 2]])

In [34]:
a = np.arange(1,16,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [35]:
a.reshape(2,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [36]:
a.reshape(4,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [ ]:
# concate iki numpy concate etme

In [38]:
a = np. random.randint(1,6, size= (5))
a

array([3, 3, 4, 4, 1])

In [40]:
b = np.random.randint(2,7, size = (5))
b

array([5, 6, 4, 3, 2])

In [43]:
c = np.concatenate([a,b])
c

array([3, 3, 4, 4, 1, 5, 6, 4, 3, 2])

In [46]:
a = np.random.randint(2,7,size= 4)
b= np.random.randint(10,14, size = 6)
c = np.concatenate([a,b])
c

array([ 3,  3,  5,  3, 11, 13, 12, 13, 11, 10])

In [49]:
a = np.random.randint(2,7, size = (3,4))
b = np.random.randint(8,14,size = (3,4))


array([[ 3,  4,  3,  5],
       [ 6,  5,  2,  5],
       [ 6,  3,  4,  4],
       [13, 10, 12, 11],
       [10,  8, 12, 12],
       [11, 12, 11, 10]])

In [50]:
a

array([[3, 4, 3, 5],
       [6, 5, 2, 5],
       [6, 3, 4, 4]])

In [51]:
b

array([[13, 10, 12, 11],
       [10,  8, 12, 12],
       [11, 12, 11, 10]])

In [52]:
c

array([[ 3,  4,  3,  5],
       [ 6,  5,  2,  5],
       [ 6,  3,  4,  4],
       [13, 10, 12, 11],
       [10,  8, 12, 12],
       [11, 12, 11, 10]])

In [54]:
a = np.random.randint(3,9, size = (3,4))
a

array([[3, 8, 8, 6],
       [8, 3, 3, 3],
       [5, 6, 6, 4]])

In [57]:
b = np.random.randint(5,15, size = (3,4))
b

array([[ 7, 14, 12,  5],
       [13, 14,  9,  6],
       [ 8, 14,  5,  7]])

In [61]:
c = np.concatenate([a,b],axis=0)
c

array([[ 3,  8,  8,  6],
       [ 8,  3,  3,  3],
       [ 5,  6,  6,  4],
       [ 7, 14, 12,  5],
       [13, 14,  9,  6],
       [ 8, 14,  5,  7]])

In [63]:
c = np.concatenate([a,b], axis = 1)
c

array([[ 3,  8,  8,  6,  7, 14, 12,  5],
       [ 8,  3,  3,  3, 13, 14,  9,  6],
       [ 5,  6,  6,  4,  8, 14,  5,  7]])

In [ ]:
# concatenate yaparken sütün sayıları aynı olmak zorunda

In [71]:
a = np.random.randint(3,5, size = (3,6))
b= np.random.randint(5,15, size = (4,6))
c = np.concatenate([a,b],axis = 0)
c

array([[ 4,  4,  4,  3,  4,  4],
       [ 4,  3,  4,  3,  4,  4],
       [ 4,  3,  4,  4,  3,  4],
       [ 5, 14, 12, 13,  6,  9],
       [11,  9, 12,  7, 10, 13],
       [ 6,  8, 13,  6, 13, 12],
       [14,  6, 10,  8, 14, 13]])

In [75]:
c.ndim  # kaç boyutlu olduğu 

2

In [76]:
c.size

42

In [78]:
c.shape

(7, 6)

In [79]:
c.mean()  # aritmetik ortalama

7.404761904761905

In [80]:
c.std()

3.9161419535626534

In [82]:
c

array([[ 4,  4,  4,  3,  4,  4],
       [ 4,  3,  4,  3,  4,  4],
       [ 4,  3,  4,  4,  3,  4],
       [ 5, 14, 12, 13,  6,  9],
       [11,  9, 12,  7, 10, 13],
       [ 6,  8, 13,  6, 13, 12],
       [14,  6, 10,  8, 14, 13]])

In [88]:
np.sort(c, axis = 1) # satırları kendi arasında sıraladı

array([[ 3,  4,  4,  4,  4,  4],
       [ 3,  3,  4,  4,  4,  4],
       [ 3,  3,  4,  4,  4,  4],
       [ 5,  6,  9, 12, 13, 14],
       [ 7,  9, 10, 11, 12, 13],
       [ 6,  6,  8, 12, 13, 13],
       [ 6,  8, 10, 13, 14, 14]])

In [89]:
np.sort(c, axis = 0) # sütunları sıraladı

array([[ 4,  3,  4,  3,  3,  4],
       [ 4,  3,  4,  3,  4,  4],
       [ 4,  4,  4,  4,  4,  4],
       [ 5,  6, 10,  6,  6,  9],
       [ 6,  8, 12,  7, 10, 12],
       [11,  9, 12,  8, 13, 13],
       [14, 14, 13, 13, 14, 13]])

In [97]:
a = np.arange(2,22).reshape(5,4)
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [98]:
a[1,1] # 1. satır ve 1. sütun 

7

In [99]:
a[:,2]

array([ 4,  8, 12, 16, 20])

In [100]:
a[0:2,3]

array([5, 9])

In [101]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [103]:
a[0,0]

2

In [105]:
a[:,2]

array([ 4,  8, 12, 16, 20])

In [106]:
a[1:3,0:2]

array([[ 6,  7],
       [10, 11]])

In [109]:
a = np.random.randint(2,10,size = (3,4))
a

array([[2, 3, 2, 8],
       [9, 2, 2, 2],
       [7, 3, 7, 8]])

In [111]:
a[1,-1]

2

In [113]:
a<5  # true ya da false döndürür

array([[ True,  True,  True, False],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [115]:
a[a<5] # 5'ten küçükleri tek bir dizi olarak yazdırıyor

array([2, 3, 2, 2, 2, 2, 3])

In [116]:
a[0:2]>7 # ilk iki satıra göre kıyaslama yaptık

array([[False, False, False,  True],
       [ True, False, False, False]])

In [117]:
a[0:2<5]

array([[2, 3, 2, 8]])

In [118]:
a

array([[2, 3, 2, 8],
       [9, 2, 2, 2],
       [7, 3, 7, 8]])

In [119]:
np.add(a,13)  # tüm elemanlarına 13 ekledik.

array([[15, 16, 15, 21],
       [22, 15, 15, 15],
       [20, 16, 20, 21]])

In [120]:
np.subtract(a,5)  # tüm verilerden 5 çıkardık

array([[-3, -2, -3,  3],
       [ 4, -3, -3, -3],
       [ 2, -2,  2,  3]])

In [121]:
np.multiply(a,3)  # tüm değerleri 3 ile çarptık

array([[ 6,  9,  6, 24],
       [27,  6,  6,  6],
       [21,  9, 21, 24]])

In [122]:
np.divide(a,2)  # tüm verileri ikiye böldük

array([[1. , 1.5, 1. , 4. ],
       [4.5, 1. , 1. , 1. ],
       [3.5, 1.5, 3.5, 4. ]])

In [123]:
np.mod(a,3)  # modulüs

array([[2, 0, 2, 2],
       [0, 2, 2, 2],
       [1, 0, 1, 2]], dtype=int32)

In [124]:
np.absolute(a)  # mutlak değerlerini aldık 

array([[2, 3, 2, 8],
       [9, 2, 2, 2],
       [7, 3, 7, 8]])

In [125]:
np.cos(a[0])  # cosinüs hesaplama

array([-0.41614684, -0.9899925 , -0.41614684, -0.14550003])

In [126]:
np.sin(a)

array([[0.90929743, 0.14112001, 0.90929743, 0.98935825],
       [0.41211849, 0.90929743, 0.90929743, 0.90929743],
       [0.6569866 , 0.14112001, 0.6569866 , 0.98935825]])

In [127]:
np.log10(a)

array([[0.30103   , 0.47712125, 0.30103   , 0.90308999],
       [0.95424251, 0.30103   , 0.30103   , 0.30103   ],
       [0.84509804, 0.47712125, 0.84509804, 0.90308999]])

In [129]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 1.41421356, 2.82842712],
       [3.        , 1.41421356, 1.41421356, 1.41421356],
       [2.64575131, 1.73205081, 2.64575131, 2.82842712]])