In [1]:
import numpy as np

In [2]:
np.__version__


'1.19.2'

In [3]:
arr = np.array([1,2,3],dtype = "float32")
arr

array([1., 2., 3.], dtype=float32)

In [4]:
arr = np.zeros((3,5), dtype = "float32")
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [5]:
arr = np.ones((4,6),dtype="int64")
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int64)

In [6]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.86889016, 0.5198041 , 0.46827679],
       [0.69579525, 0.96337238, 0.38577239],
       [0.39683048, 0.14254131, 0.35447629]])

In [10]:
arr = np.random.normal(10, 4, (3,4)) #ortalamasi=10, standart sapmasi=4 olan 3x4'luk matris
arr

array([[10.85352699, 10.86178017,  8.75594337, 16.06256735],
       [10.38538947, 10.69949422,  8.7395477 , 11.12497678],
       [ 8.00285317, 16.44236946,  5.1109939 ,  6.11969105]])

In [11]:
np.random.randint(0, 10, (3,3))
#0 ile 10 araliginde rastgele int degerlerden 3x3'luk matris


array([[5, 8, 0],
       [8, 2, 5],
       [4, 0, 2]])

In [12]:
NumPy Array Özellikleri
ndim: boyut sayısı
shape: boyut bilgisi
size: toplam eleman sayısı
dtype: array veri tipi

SyntaxError: invalid syntax (<ipython-input-12-a05e924021ba>, line 1)

In [ ]:
arr.ndim # boyut sayısı

In [ ]:
arr.shape  # boyut bilgisi

In [ ]:
arr.size  # toplam eleman sayısı

In [ ]:
arr.dtype  # array veri tipi

In [ ]:
# iki boyutlu dizi oluşturalım


In [ ]:
arr = np.random.randint(10,20,size = (5,4))


### Reshaping (Array'i Yeniden Şekillendirme)
Elimizde var olan bir array'i yeniden şekillendirme işlemi yapacağız. Örneğin elimizde bir array olsun ve bunu yeniden boyutlandıralım.

Fonskiyonlarımızın ürettiği çıktılar tek bir boyutta, tek bir array formunda gerçekleşebiliyor.

Bunları bazen tek boyuttan 2 boyuta ya da 2 boyuttan tek boyuta indirgeme işlemi gerekebiliyor.

Bu ihtiyaçlarla Reshape fonksiyonu ile başa çıkmış oluyoruz.

In [ ]:
a = np.arange(0,100,10)  
a


In [ ]:
a.reshape(5,2)

In [ ]:
a.ndim

#### Not: Tek boyutlu array: Vektör, 2 boyutlu array: Matris.



In [ ]:
Elimizdeki tek boyutlu array'i 2 boyutlu matris'e çevirmek istiyoruz ama tek boyuttaki bilgisi de olduğu şekilde kalsın.



In [ ]:
x = np.arange(1,10)
x

In [ ]:
x = np.array(x, ndmin = 2)

In [ ]:
x.ndim

In [ ]:
Concantenation (Array Birleştirme)
concatenate() fonksiyonu ile array’leri birleştirebiliriz.

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
t = np.array([7,8,9])


In [ ]:
t = np.concatenate([x,y,t])

In [ ]:
t

In [ ]:
# iki boyutlu dizilerde birleştirme yaparken satır sayısının ya da sütun sayısının 
# eşit olması lazım aksi halde concatenate yaparken hata verir

In [ ]:
a = np.random.randint(1,10, size = (3,5))
b = np.random.randint(10,20, size = (3,7))
c = np.concatenate([a,b], axis = 1)

In [ ]:
# satır sayıları eşit olursa;
# axis = 1 ile birleştirme yapılır
# sütunları yanyana ekler. satır sayısı sabit kalır

In [ ]:
# sütun sayıları eşit ise;
# axis = 0 ile birleştrime yapılır
# satırları alt alta ekler
# sütun sayıları aynı kalır

In [ ]:
x = np.random.randint(1,10, size = (3,5))
y = np.random.randint(10,20, size = (5,5))

In [ ]:
x

In [ ]:
y

In [ ]:
z = np.concatenate([x,y],axis = 0)
z

### Splitting (Array Ayırma)
split() fonksiyonu kullanılır.

In [13]:
x = np.array([1,2,3,88,99,111,4,5,6])

In [14]:
np.split(x, [3,5]) #3. indise kadar ayir, sonra 5. indise kadar ayir, sonra sona kadar.

[array([1, 2, 3]), array([88, 99]), array([111,   4,   5,   6])]

In [ ]:
split fonksiyonuna girilen indis sayısı n ise çıktı array sayısı n+1 olur



In [15]:
a,b,c = np.split(x,[3,6])

In [16]:
a

array([1, 2, 3])

In [17]:
b

array([ 88,  99, 111])

In [18]:
c

array([4, 5, 6])

In [ ]:
İki boyutlu array ayırma

vsplit() : dikey olarak ayırmak için kullanılır.

hsplit() : yatay olarak ayırmak için kullanılır.

In [19]:
arr = np.arange(16).reshape(4,4)

In [20]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.vsplit(arr, [2])     # yataydaki 2. indise kadar ve sonrasini ayir.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [23]:
arr = np.arange(30).reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [24]:
alt, orta, üst = np.vsplit(arr, [2,5])

In [25]:
alt

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
orta

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
üst

array([[25, 26, 27, 28, 29]])

In [28]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
np.hsplit(arr, [2,])    #dikeyde 2. indise kadar ve sonrasini ayir.

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19],
        [22, 23, 24],
        [27, 28, 29]])]

In [ ]:
Sorting (Sıralama)
sort() fonskiyonunu kullanırız.

In [31]:
arr = np.array([2,3,1,6,5,4])

In [32]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [33]:
arr  # orijinal yapı değişmedi

array([2, 3, 1, 6, 5, 4])

In [35]:
arr.sort()  # orijinal yapıyı değiştirdi
arr

array([1, 2, 3, 4, 5, 6])

### Matris Sıralama



In [36]:
arr = np.random.normal(20,3,(3,3)) #ortalamasi 20, standart sapmasi 3 olan 3x3 matris.

In [37]:
arr

array([[19.85490298, 23.35906648, 19.14439025],
       [23.15795409, 18.24727525, 18.51320347],
       [23.62312873, 20.78255581, 18.0170277 ]])

In [38]:
np.sort(arr, axis=1)     #Her bir satiri kendi icinde siralar.

array([[19.14439025, 19.85490298, 23.35906648],
       [18.24727525, 18.51320347, 23.15795409],
       [18.0170277 , 20.78255581, 23.62312873]])

In [39]:
np.sort(arr, axis=0) #Sutunlara gore siralama yapar.

array([[19.85490298, 18.24727525, 18.0170277 ],
       [23.15795409, 20.78255581, 18.51320347],
       [23.62312873, 23.35906648, 19.14439025]])

### Index ile Elemana Erişmek
Tek boyutlu array'lerde eleman yakalama işlemleri listeler ile aynıdır.

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[1]  # 1. index te yer alan eleman

1

In [43]:
arr[-1]  # en sonda yer alan eleman

9

### Matrislerde elemana erişme işlemleri:



In [46]:
arr = np.random.randint(10,size = (3,3))
arr

array([[0, 3, 2],
       [5, 5, 9],
       [2, 3, 4]])

In [47]:
arr[0,0]  # 0'a 0 indexte yer alan eleman erişmek

0

In [48]:
arr[2,1]  # index 2'ye 1 elemana erişmek

3

In [50]:
# Belirlenen index lere değer atama işlemi de yapılabilir. 
arr[2,1] = 99
arr[2,1]

99

In [55]:
arr[1,2] = 8.88 #float eklemek istiyoruz anca ondalik kismini keserek ekleyecek.
arr            #Daha onceden olusturulan bir array'in tipi sonradan ekleme ile degismez.

array([[ 0,  3,  2],
       [ 5,  5,  8],
       [ 2, 99,  4]])

### Slicing (Array Alt Küme İşlemleri)
Tek boyutlu array'lerde slicing işlemleri

In [58]:
arr = np.arange(20,30)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
arr[0:3]  # listelerdeki ile aynı mantık. 

array([20, 21, 22])

In [60]:
arr[:3]

array([20, 21, 22])

In [61]:
arr[2:5]

array([22, 23, 24])

In [62]:
arr[::2]

array([20, 22, 24, 26, 28])

In [63]:
arr[-5:-1]

array([25, 26, 27, 28])

#### Matrislerde Slicing İşlemleri



In [64]:
arr = np.random.randint(10,size = (5,5))

In [65]:
arr

array([[1, 5, 1, 6, 6],
       [7, 5, 8, 3, 0],
       [7, 9, 5, 3, 6],
       [2, 8, 1, 6, 2],
       [3, 3, 6, 6, 2]])

In [70]:
arr[:,1:3] # bütün satılar ve birinci sütun

array([[5, 1],
       [5, 8],
       [9, 5],
       [8, 1],
       [3, 6]])

In [73]:
arr [0,:]# 0. satır ve bütün sütünlar.

array([1, 5, 1, 6, 6])

In [74]:
#1. ve 2. satirlar, 1. sutun
arr[1:3,1]

array([5, 9])

### Alt Küme Üzerinde İşlem Yapmak
Önceki bölümde array'lerin alt kümelerine eriştik fakat burada şöyle bir durum söz konusu;

Örneğin bir array'in alt kümesine eriştikten sonra bunu isimlendirip kaydettiğimizi düşünelim.

Bu kaydetmiş olduğumuz isimlendirme üzerinde bir değişiklik yaptığımızda array'in orjinali de değişiyordu.

Fakat bazen seçilen array'in alt kümesinde o alt kümeye özel işlemler yapılmak istenebilir.

İşte bu yüzden alt kümeleri bağımsızlaştırmak isimli bir işlem yapılması gerekiyor.

In [75]:
a = np.random.randint(10, size = (5,5))

In [76]:
a

array([[9, 8, 6, 7, 8],
       [2, 3, 6, 5, 1],
       [6, 8, 2, 4, 4],
       [0, 5, 6, 5, 0],
       [5, 1, 9, 0, 5]])

In [77]:
alt_a = a[0:3,0:2]  # alt küme tanımladık ve değişkene atadık

In [78]:
alt_a

array([[9, 8],
       [2, 3],
       [6, 8]])

In [80]:
alt_a[0,0] = 99  # belirlediğimiz indexe elaman atadık
alt_a

array([[99,  8],
       [ 2,  3],
       [ 6,  8]])

In [81]:
a  # orijinal matrisimiz de etkilendi. 

array([[99,  8,  6,  7,  8],
       [ 2,  3,  6,  5,  1],
       [ 6,  8,  2,  4,  4],
       [ 0,  5,  6,  5,  0],
       [ 5,  1,  9,  0,  5]])

In [ ]:
Bu durum bazen çok iş görebilmekte.

Çok büyük boyutta array'ler elimizde olduğunda onların bazı parçalarını seçip spesifik 
olarak onların üzerinde çalışıp ana parçanın üzerinde değişiklik yapmak açısından çok işe yarar.

copy() metodunu kullanarak bu durumdan vazgeçebiliriz.

In [83]:
alt_b = a[0:3, 0:2].copy()
alt_b

array([[99,  8],
       [ 2,  3],
       [ 6,  8]])

In [85]:
alt_b[0,0] = 1
alt_b

array([[1, 8],
       [2, 3],
       [6, 8]])

In [86]:
a  # orijinal dizi etkilenmedi.

array([[99,  8,  6,  7,  8],
       [ 2,  3,  6,  5,  1],
       [ 6,  8,  2,  4,  4],
       [ 0,  5,  6,  5,  0],
       [ 5,  1,  9,  0,  5]])

### Fancy Index ile Elemanlara Erişmek
Fancy Index kavramı ilerleyen bölümlerde bizim için en önemli kavramlardan birisi olacak.

Bize hem Pandas data frame'lerinde hem de NumPy array'lerinde ileri düzey eleman seçme imkanları
vermektedir.

In [90]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [91]:
# klasik yöntem ile önce indexleri getirelim.
[a[1],a[3],a[5]]

[3, 9, 15]

In [92]:
# şimdi aynı indexleri farklı bir yöntem ile çağıralım
index_list = [1,3,5]
a[index_list]  # buna fancy index nedir?

array([ 3,  9, 15])

### Matrislerde Fancy Index Kullanımı



In [95]:
a = np.arange(3,27).reshape(8,3)
a

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [96]:
satır = [1,3,5]
sütun = [0,1,2]
a[satır,sütun]

array([ 6, 13, 20])

In [ ]:
# basit index ile fancy beraber kullanalım 

In [97]:
a[[1,2],0]

array([6, 9])

### Koşullu Eleman İşlemleri¶


In [99]:
v = np.array([1,2,3,4,5])
v> 3

array([False, False, False,  True,  True])

In [100]:
v < 3

array([ True,  True, False, False, False])

In [102]:
v[v < 3]  # fancy index

array([1, 2])

In [103]:
v[v>2]

array([3, 4, 5])

In [104]:
v[v == 2]

array([2])

In [105]:
v[v != 2]

array([1, 3, 4, 5])

In [106]:
v * 2

array([ 2,  4,  6,  8, 10])

In [107]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [108]:
v + 3

array([4, 5, 6, 7, 8])

### Matematiksel İşlemler

In [ ]:
# ufunc fonksiyonları


In [111]:
dizi_1 = np.arange(5)
dizi_1

array([0, 1, 2, 3, 4])

In [117]:
dizi_2 = np.arange(5,10)
dizi_2

array([5, 6, 7, 8, 9])

In [115]:
dizi_1 + dizi_2

array([ 5,  7,  9, 11, 13])

In [118]:
dizi_1 - dizi_2

array([-5, -5, -5, -5, -5])

In [119]:
np.subtract(dizi_1, dizi_2)

array([-5, -5, -5, -5, -5])

In [120]:
np.add(dizi_1, dizi_2)

array([ 5,  7,  9, 11, 13])

In [121]:
np.multiply(dizi_1,dizi_2)

array([ 0,  6, 14, 24, 36])

In [124]:
np.divide(dizi_1, dizi_2)

dtype('float64')