In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [6]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array((1,2,3,4,5,6))
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
0-D Arrays


In [10]:
a = np.array(55)
a

array(55)

In [ ]:
1-D Arrays


In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# boyut ayarlamak için ndmin() kullanılır

In [16]:
a = np.array([1,2,3], ndmin= 5)
a.ndim

5

In [18]:
arr = np.array([1, 2, 3, 4])
bar = np.array([5, 6, 7, 8])
c = np.concatenate([arr,bar])

print(c)

[1 2 3 4 5 6 7 8]


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
print(arr[1, 1, 2])

12


In [22]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
print(arr[0:2, 2])


[3 8]


In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [31]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr

array([10, 15, 20, 25, 30, 35, 40])

In [32]:
arr[1:5:2]

array([15, 25])

In [36]:
a = np.array(["a","b","c","d","e","f"])
a

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [37]:
a.dtype

dtype('<U1')

In [47]:
arr = np.array(['apple', 'bananaaaaa', 'cherry'],dtype = "U")
arr.dtype

dtype('<U10')

In [54]:
arr = np.array(['1', '2', 3], dtype='i')
arr

array([1, 2, 3], dtype=int32)

In [55]:
arr = np.array(['a', '2', 3], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

In [58]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = np.array(arr,dtype= "str")
new_arr

array(['1.1', '2.1', '3.1'], dtype='<U32')

In [72]:
arr = np.array([1.1, 2.1, 3.1])
new_arr = arr.astype(int)
new_arr

array([1, 2, 3])

In [69]:
arr = np.array([1, 0, 3])
new_arr = arr.astype("bool")
new_arr

array([ True, False,  True])

In [67]:
new_arr_2 = np.array(arr,dtype="bool")
new_arr_2

array([ True, False,  True])

In [ ]:
arr = []