In [1]:
import numpy as np

In [2]:
j = [0,2,4]
k = [1,3,5]
m = [6,8,10]
# yukarıdaki listeleri tek tek numpy array yapalım
j = np.array(j)
k = np.array(k)
m = np.array(m)

In [5]:
type_of_var = type(j),type(k), type(m)
type_of_var

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
j+k  # index numaralarına göre topluyor.

array([1, 5, 9])

In [ ]:
# array içindeki verilerin tipini kontrol etmek için dtype kullanılır


In [8]:
j.dtype

dtype('int32')

In [9]:
np_array = np.array([1.,2,3,6.4])
np_array

array([1. , 2. , 3. , 6.4])

In [10]:
np_array.dtype

dtype('float64')

In [11]:
# veri tipini değişmek için

In [13]:
liste = [2,5,6,9]
ndarray = np.array(liste, dtype = str)
ndarray

array(['2', '5', '6', '9'], dtype='<U1')

In [18]:
# fill zero or ones
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [20]:
zeros = np.zeros(4, dtype = int)
zeros

array([0, 0, 0, 0])

In [23]:
ones = np.ones(6, dtype = int)
ones

array([1, 1, 1, 1, 1, 1])

In [25]:
# rastgele sayılar ile dizi oluşturmak için
ndarray = np.random.randint(2,10, size = 5)
ndarray

array([4, 3, 4, 9, 7])

In [28]:
ndarray = np.random.randint(100,200, size = (4,3))
ndarray

array([[161, 163, 106],
       [197, 128, 165],
       [185, 104, 191],
       [101, 127, 105]])

In [ ]:
# concatenate 

In [30]:
dizi1 = np.random.randint(10,30, size = (5,3))
dizi2 = np.random.randint(20,60, size = (5,4))

In [36]:
dizi1

array([[24, 27, 11],
       [11, 21, 25],
       [15, 28, 10],
       [27, 24, 10],
       [15, 16, 24]])

In [37]:
dizi2

array([[35, 53, 35, 27],
       [39, 56, 28, 23],
       [20, 29, 47, 51],
       [28, 48, 39, 59],
       [55, 32, 49, 54]])

In [35]:
dizi3 = np.concatenate([dizi1,dizi2], axis = 1)
dizi3
# sütunları birleştirtik. 

array([[24, 27, 11, 35, 53, 35, 27],
       [11, 21, 25, 39, 56, 28, 23],
       [15, 28, 10, 20, 29, 47, 51],
       [27, 24, 10, 28, 48, 39, 59],
       [15, 16, 24, 55, 32, 49, 54]])

In [ ]:
# herbir satırda yer alan eleman sayıları eşit olmadığından
# satır bazında birleştirme yapılamaz
# concatenate yapabilmek için en az bir boyutunun uzunluğu
# eşit olmak zorunda. satır sayıları eşit ise sütunları 
# birleştirebiliriz.
# sütun sayıları (dizinin her bir indexinin eleman sayısı) eşit ise satırları
# birleştirebiliriz

In [39]:
# sütun sayıları eşit olan iki diziyi birleştirelim
dizi_a = np.random.randint(10,30, size = (4,5))
dizi_a

array([[22, 12, 26, 12, 12],
       [14, 26, 15, 19, 15],
       [12, 26, 14, 18, 28],
       [11, 25, 23, 19, 20]])

In [43]:
dizi_b = np.random.randint(50,60, size = (7,5))
dizi_b

array([[50, 56, 50, 50, 56],
       [51, 51, 55, 50, 55],
       [56, 59, 53, 56, 56],
       [57, 59, 56, 59, 51],
       [59, 57, 59, 52, 54],
       [50, 59, 57, 53, 51],
       [53, 57, 51, 53, 51]])

In [47]:
# sütun sayıları ( yani her bir indexinin sayıları ) eşit olduğundan
dizi_c = np.concatenate([dizi_a, dizi_b], axis = 0)
dizi_c

array([[22, 12, 26, 12, 12],
       [14, 26, 15, 19, 15],
       [12, 26, 14, 18, 28],
       [11, 25, 23, 19, 20],
       [50, 56, 50, 50, 56],
       [51, 51, 55, 50, 55],
       [56, 59, 53, 56, 56],
       [57, 59, 56, 59, 51],
       [59, 57, 59, 52, 54],
       [50, 59, 57, 53, 51],
       [53, 57, 51, 53, 51]])

In [ ]:
# dimension yani boyut için ndim