In [1]:
import numpy as np

In [2]:
np.__version__


'1.19.2'

In [3]:
arr = np.array([1,2,3],dtype = "float32")
arr

array([1., 2., 3.], dtype=float32)

In [4]:
arr = np.zeros((3,5), dtype = "float32")
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [5]:
arr = np.ones((4,6),dtype="int64")
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int64)

In [6]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.84765879, 0.48757734, 0.93556539],
       [0.36277685, 0.02516244, 0.64880534],
       [0.99831723, 0.5823088 , 0.14861924]])

In [10]:
arr = np.random.normal(10, 4, (3,4)) #ortalamasi=10, standart sapmasi=4 olan 3x4'luk matris
arr

array([[ 9.76417573, 10.93161253,  0.37132958,  8.21049319],
       [ 6.22687116, 11.67083456,  3.6290653 , 12.94794557],
       [ 9.68128429, 12.917559  ,  5.72122427, 12.80391588]])

In [11]:
np.random.randint(0, 10, (3,3))
#0 ile 10 araliginde rastgele int degerlerden 3x3'luk matris


array([[7, 1, 2],
       [8, 3, 2],
       [6, 5, 4]])

In [12]:
NumPy Array Özellikleri
ndim: boyut sayısı
shape: boyut bilgisi
size: toplam eleman sayısı
dtype: array veri tipi

SyntaxError: invalid syntax (<ipython-input-12-a05e924021ba>, line 1)

In [ ]:
arr.ndim # boyut sayısı

In [ ]:
arr.shape  # boyut bilgisi

In [ ]:
arr.size  # toplam eleman sayısı

In [ ]:
arr.dtype  # array veri tipi

In [ ]:
# iki boyutlu dizi oluşturalım


In [ ]:
arr = np.random.randint(10,20,size = (5,4))


### Reshaping (Array'i Yeniden Şekillendirme)
Elimizde var olan bir array'i yeniden şekillendirme işlemi yapacağız. Örneğin elimizde bir array olsun ve bunu yeniden boyutlandıralım.

Fonskiyonlarımızın ürettiği çıktılar tek bir boyutta, tek bir array formunda gerçekleşebiliyor.

Bunları bazen tek boyuttan 2 boyuta ya da 2 boyuttan tek boyuta indirgeme işlemi gerekebiliyor.

Bu ihtiyaçlarla Reshape fonksiyonu ile başa çıkmış oluyoruz.

In [25]:
a = np.arange(0,100,10)  
a


array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
a.reshape(5,2)

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [27]:
a.ndim

1

#### Not: Tek boyutlu array: Vektör, 2 boyutlu array: Matris.



In [30]:
Elimizdeki tek boyutlu array'i 2 boyutlu matris'e çevirmek istiyoruz ama tek boyuttaki bilgisi de olduğu şekilde kalsın.



1

In [51]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x = np.array(x, ndmin = 2)

In [50]:
x.ndim

2

In [ ]:
Concantenation (Array Birleştirme)
concatenate() fonksiyonu ile array’leri birleştirebiliriz.

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])
t = np.array([7,8,9])


array([1, 2, 3, 4, 5, 6])

In [59]:
t = np.concatenate([x,y,t])

In [60]:
t

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# iki boyutlu dizilerde birleştirme yaparken satır sayısının ya da sütun sayısının 
# eşit olması lazım aksi halde concatenate yaparken hata verir

In [62]:
a = np.random.randint(1,10, size = (3,5))
b = np.random.randint(10,20, size = (3,7))
c = np.concatenate([a,b], axis = 1)

In [63]:
# satır sayıları eşit olursa;
# axis = 1 ile birleştirme yapılır
# sütunları yanyana ekler. satır sayısı sabit kalır

array([[ 7,  1,  3,  2,  5, 12, 11, 15, 15, 18, 11, 16],
       [ 8,  8,  3,  4,  5, 12, 16, 17, 19, 14, 11, 12],
       [ 4,  4,  9,  9,  1, 12, 10, 13, 15, 19, 12, 19]])

In [64]:
# sütun sayıları eşit ise;
# axis = 0 ile birleştrime yapılır
# satırları alt alta ekler
# sütun sayıları aynı kalır

In [70]:
x = np.random.randint(1,10, size = (3,5))
y = np.random.randint(10,20, size = (5,5))

In [71]:
x

array([[7, 1, 5, 4, 6],
       [2, 8, 6, 8, 5],
       [5, 3, 7, 4, 4]])

In [72]:
y

array([[19, 18, 17, 14, 18],
       [18, 19, 12, 11, 19],
       [14, 18, 17, 19, 19],
       [12, 11, 13, 11, 14],
       [11, 14, 17, 19, 12]])

In [74]:
z = np.concatenate([x,y],axis = 0)
z

array([[ 7,  1,  5,  4,  6],
       [ 2,  8,  6,  8,  5],
       [ 5,  3,  7,  4,  4],
       [19, 18, 17, 14, 18],
       [18, 19, 12, 11, 19],
       [14, 18, 17, 19, 19],
       [12, 11, 13, 11, 14],
       [11, 14, 17, 19, 12]])