In [1]:
import numpy as np

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(6,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [8]:
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3,2,2)
arr




array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [10]:
list("abcd")

['a', 'b', 'c', 'd']

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)


ValueError: cannot reshape array of size 8 into shape (3,3)

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(4, 2)
newarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
print(arr.base)

None


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4, -1)  # -1 değeri ile sütun sayısını otomatik doldurur
# sadece tek boyutlu dizileri shape ederken kullanılır

In [21]:
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
newarr.reshape(-1)  # çok boyutlu diziyi düzleştirmek için 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
newarr

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)
  

1
2
3
4
5
6


In [38]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], ndmin = 10)

for x in np.nditer(arr):
  print(x)


1
2
3
4
5
6
7
8


In [40]:
arr = np.array([1, 2, 3])
f

[((0,), 1), ((1,), 2), ((2,), 3)]

In [47]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

In [42]:
arr1

array([[1, 2],
       [3, 4]])

In [43]:
arr2

array([[5, 6],
       [7, 8]])

In [48]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
arr3 = np.concatenate([arr1,arr2])

arr3

array([1, 2, 3, 4, 5, 6])

In [53]:
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [56]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])